//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stgWifi8.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifipath.apphb.com/Webservices/MovieType.asmx")]
        public string stgWifi8_com_apphb_stgwifipath_MovieType {
            get {
                return ((string)(this["stgWifi8_com_apphb_stgwifipath_MovieType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifipath.apphb.com/Webservices/Movie.asmx")]
        public string stgWifi8_com_apphb_stgwifipathMovie_Movie {
            get {
                return ((string)(this["stgWifi8_com_apphb_stgwifipathMovie_Movie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dreamshop.apphb.com/WebServices/serProduct.asmx")]
        public string stgWifi8_com_apphb_dreamshopProd_serProduct {
            get {
                return ((string)(this["stgWifi8_com_apphb_dreamshopProd_serProduct"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifipath.apphb.com/Webservices/Users.asmx")]
        public string stgWifi8_com_apphb_stgwifipathUsers_Users {
            get {
                return ((string)(this["stgWifi8_com_apphb_stgwifipathUsers_Users"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:57306/Webservices/Story.asmx")]
        public string stgWifi8_StoryService_Story {
            get {
                return ((string)(this["stgWifi8_StoryService_Story"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:57306/Webservices/Users.asmx")]
        public string stgWifi8_UsersService_Users {
            get {
                return ((string)(this["stgWifi8_UsersService_Users"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:57306/Webservices/Radio.asmx")]
        public string stgWifi8_RadioService_Radio {
            get {
                return ((string)(this["stgWifi8_RadioService_Radio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:57306/Webservices/Music.asmx")]
        public string stgWifi8_MusicService_Music {
            get {
                return ((string)(this["stgWifi8_MusicService_Music"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifipath.apphb.com/Webservices/MyList.asmx")]
        public string stgWifi8_com_apphb_stgwifipathMyList_MyList {
            get {
                return ((string)(this["stgWifi8_com_apphb_stgwifipathMyList_MyList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifi.com/Webservices/Users.asmx")]
        public string stgWifi8_com_stgwifiUsers_Users {
            get {
                return ((string)(this["stgWifi8_com_stgwifiUsers_Users"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifi.com/Webservices/Radio.asmx")]
        public string stgWifi8_com_stgwifiRadio_Radio {
            get {
                return ((string)(this["stgWifi8_com_stgwifiRadio_Radio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifi.com/Webservices/Music.asmx")]
        public string stgWifi8_com_stgwifiMusic_Music {
            get {
                return ((string)(this["stgWifi8_com_stgwifiMusic_Music"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifi.com/Webservices/Story.asmx")]
        public string stgWifi8_com_stgwifiStory_Story {
            get {
                return ((string)(this["stgWifi8_com_stgwifiStory_Story"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifi.com/Webservices/ProductCategory.asmx")]
        public string stgWifi8_com_stgwifiProductCategory_ProductCategory {
            get {
                return ((string)(this["stgWifi8_com_stgwifiProductCategory_ProductCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9482/Webservices/ProductCategory.asmx")]
        public string stgWifi8_ProductCategoryService_ProductCategory {
            get {
                return ((string)(this["stgWifi8_ProductCategoryService_ProductCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:21476/Webservices/Product.asmx")]
        public string stgWifi8_ProductService_Product {
            get {
                return ((string)(this["stgWifi8_ProductService_Product"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifi.com/Webservices/Product.asmx")]
        public string stgWifi8_com_stgwifiProduct_Product {
            get {
                return ((string)(this["stgWifi8_com_stgwifiProduct_Product"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifi.com/Webservices/Merchant.asmx")]
        public string stgWifi8_com_stgwifiMerchant_Merchant {
            get {
                return ((string)(this["stgWifi8_com_stgwifiMerchant_Merchant"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:18597/Webservices/Merchant.asmx")]
        public string stgWifi8_MerchantService_Merchant {
            get {
                return ((string)(this["stgWifi8_MerchantService_Merchant"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:11807/Webservices/MerchantAddress.asmx")]
        public string stgWifi8_MerchantAddressService_MerchantAddress {
            get {
                return ((string)(this["stgWifi8_MerchantAddressService_MerchantAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stgwifi.com:15531/Webservices/MerchantAddress.asmx")]
        public string stgWifi8_com_stgwifiMerchantAddress_MerchantAddress {
            get {
                return ((string)(this["stgWifi8_com_stgwifiMerchantAddress_MerchantAddress"]));
            }
        }
    }
}
