//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stgWifi8.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.serBuyerSoap")]
    public interface serBuyerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_GetBuyerIdForCon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_GetBuyerIdForCon(string BuyeruserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_Login(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_GetPurchaseByMerchantbname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_GetPurchaseByMerchantbname(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_GetPurchaseByCatname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_GetPurchaseByCatname(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_GetPurchase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_GetPurchase(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_GetGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_GetGeneral(int buyerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_CreateBuyerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_CreateBuyerId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBuyer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateBuyer(System.Data.DataSet dataSet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serBuyerSoapChannel : stgWifi8.ServiceReference2.serBuyerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serBuyerSoapClient : System.ServiceModel.ClientBase<stgWifi8.ServiceReference2.serBuyerSoap>, stgWifi8.ServiceReference2.serBuyerSoap {
        
        public serBuyerSoapClient() {
        }
        
        public serBuyerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serBuyerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serBuyerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serBuyerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataSet Buyer_GetBuyerIdForCon(string BuyeruserId) {
            return base.Channel.Buyer_GetBuyerIdForCon(BuyeruserId);
        }
        
        public System.Data.DataSet Buyer_Login(string userid, string password) {
            return base.Channel.Buyer_Login(userid, password);
        }
        
        public System.Data.DataSet Buyer_GetPurchaseByMerchantbname(string name) {
            return base.Channel.Buyer_GetPurchaseByMerchantbname(name);
        }
        
        public System.Data.DataSet Buyer_GetPurchaseByCatname(string name) {
            return base.Channel.Buyer_GetPurchaseByCatname(name);
        }
        
        public System.Data.DataSet Buyer_GetPurchase(int orderId) {
            return base.Channel.Buyer_GetPurchase(orderId);
        }
        
        public System.Data.DataSet Buyer_GetGeneral(int buyerId) {
            return base.Channel.Buyer_GetGeneral(buyerId);
        }
        
        public System.Data.DataSet Buyer_CreateBuyerId() {
            return base.Channel.Buyer_CreateBuyerId();
        }
        
        public System.Data.DataSet Buyer_GetAll() {
            return base.Channel.Buyer_GetAll();
        }
        
        public bool UpdateBuyer(System.Data.DataSet dataSet) {
            return base.Channel.UpdateBuyer(dataSet);
        }
    }
}
