//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stgWifi8.Merchants {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Merchants.serMerchantSoap")]
    public interface serMerchantSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buyer_CreateMerchantId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buyer_CreateMerchantId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetMerIdForCon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetMerIdForCon(string businessname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetBizname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetBizname(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewSavedMerchats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ViewSavedMerchats(int merchantId, int buyerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchSavedMerchant", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchSavedMerchant(string businessname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetPhoneInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetPhoneInformation(int merchantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetSecurityInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetSecurityInformation(int merchantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetOne", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetOne(int merchantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GeneralInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GeneralInformation(int merchantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetBusnameByProductDescription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetBusnameByProductDescription(string discription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetMerchantId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetMerchantId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetAllBusinessname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetAllBusinessname();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merchant_GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Merchant_GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMerchant", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateMerchant(System.Data.DataSet dataSet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serMerchantSoapChannel : stgWifi8.Merchants.serMerchantSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serMerchantSoapClient : System.ServiceModel.ClientBase<stgWifi8.Merchants.serMerchantSoap>, stgWifi8.Merchants.serMerchantSoap {
        
        public serMerchantSoapClient() {
        }
        
        public serMerchantSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serMerchantSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serMerchantSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serMerchantSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataSet Buyer_CreateMerchantId() {
            return base.Channel.Buyer_CreateMerchantId();
        }
        
        public System.Data.DataSet Merchant_GetMerIdForCon(string businessname) {
            return base.Channel.Merchant_GetMerIdForCon(businessname);
        }
        
        public System.Data.DataSet Merchant_GetBizname(int productId) {
            return base.Channel.Merchant_GetBizname(productId);
        }
        
        public System.Data.DataSet ViewSavedMerchats(int merchantId, int buyerId) {
            return base.Channel.ViewSavedMerchats(merchantId, buyerId);
        }
        
        public System.Data.DataSet SearchSavedMerchant(string businessname) {
            return base.Channel.SearchSavedMerchant(businessname);
        }
        
        public System.Data.DataSet Merchant_GetPhoneInformation(int merchantId) {
            return base.Channel.Merchant_GetPhoneInformation(merchantId);
        }
        
        public System.Data.DataSet Merchant_GetSecurityInformation(int merchantId) {
            return base.Channel.Merchant_GetSecurityInformation(merchantId);
        }
        
        public System.Data.DataSet Merchant_GetOne(int merchantId) {
            return base.Channel.Merchant_GetOne(merchantId);
        }
        
        public System.Data.DataSet Merchant_GeneralInformation(int merchantId) {
            return base.Channel.Merchant_GeneralInformation(merchantId);
        }
        
        public System.Data.DataSet Merchant_GetBusnameByProductDescription(string discription) {
            return base.Channel.Merchant_GetBusnameByProductDescription(discription);
        }
        
        public System.Data.DataSet Merchant_GetMerchantId() {
            return base.Channel.Merchant_GetMerchantId();
        }
        
        public System.Data.DataSet Merchant_GetAllBusinessname() {
            return base.Channel.Merchant_GetAllBusinessname();
        }
        
        public System.Data.DataSet Merchant_GetAll() {
            return base.Channel.Merchant_GetAll();
        }
        
        public bool UpdateMerchant(System.Data.DataSet dataSet) {
            return base.Channel.UpdateMerchant(dataSet);
        }
    }
}
